version: "3.9"

services:
    node:
        image: node:16.14
        working_dir: /app
        volumes:
            - ./:/app

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/logs:/var/log/nginx
            - ./dist:/var/www
        networks:
            mma-network:
                aliases:
                    - nginx

networks:
    mma-network:
        driver: bridge
